### ISSUE TITLE
Missing assets when running tests

### ISSUE THREAD

**Issue by lotka** [abdeladim-s/subsai#123]
I'm trying to run the tests and I have found the following files missing:

../assets/video/test1.mp4

../assets/video/test1.srt

**Comment by abdeladim-s** [comment]
Thanks @lotka for pointing that out.
I have fixed the issue, I think it should be working now.

**Comment by lotka** [comment]
Thanks!

I'm still getting some others errors with the tests but I will close this issue
